basePath: /
definitions:
  apimodel.CompleteTimetable:
    properties:
      days:
        additionalProperties:
          items:
            $ref: '#/definitions/apimodel.CompleteTimetableItem'
          type: array
        description: key format is YYYY-MM-dd or 2006-01-02
        type: object
    type: object
  apimodel.CompleteTimetableItem:
    properties:
      classes:
        items:
          $ref: '#/definitions/model.Class'
        type: array
      classrooms:
        items:
          $ref: '#/definitions/model.Classroom'
        type: array
      colors:
        items:
          type: string
        type: array
      date:
        type: string
      endtime:
        type: string
      groupnames:
        items:
          type: string
        type: array
      igroupid:
        type: string
      starttime:
        type: string
      studentids:
        items:
          type: string
        type: array
      subject:
        $ref: '#/definitions/model.Subject'
      teachers:
        items:
          $ref: '#/definitions/model.Teacher'
        type: array
      type:
        type: string
      uniperiod:
        type: string
    type: object
  apimodel.ICanteenBadRequestResponse:
    properties:
      error:
        example: username is missing
        type: string
    type: object
  apimodel.ICanteenInternalErrorResponse:
    properties:
      error:
        example: 'failed to load lunches: failed to login: Post https://example.edupage.org/login/edubarLogin.php:
          dial tcp: lookup example.edupage.org: no such host'
        type: string
    type: object
  apimodel.InternalErrorResponse:
    properties:
      error:
        example: failed to create payload
        type: string
    type: object
  apimodel.LoginBadRequestResponse:
    properties:
      error:
        example: Username and Password are required
        type: string
      success:
        example: false
        type: boolean
    type: object
  apimodel.LoginInternalErrorResponse:
    properties:
      error:
        example: 'failed to login: Post https://example.edupage.org/login/edubarLogin.php:
          dial tcp: lookup example.edupage.org: no such host'
        type: string
      success:
        example: false
        type: boolean
    type: object
  apimodel.LoginSuccessResponse:
    properties:
      error:
        example: ""
        type: string
      firstname:
        example: John
        type: string
      lastname:
        example: Doe
        type: string
      success:
        example: true
        type: boolean
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM
        type: string
    type: object
  apimodel.LoginUnauthorizedResponse:
    properties:
      error:
        example: Unexpected response from server, make sure credentials are specified
          correctly
        type: string
      success:
        example: false
        type: boolean
    type: object
  apimodel.UnauthorizedResponse:
    properties:
      error:
        example: Unauthorized
        type: string
    type: object
  apimodel.ValidateTokenSuccessResponse:
    properties:
      error:
        example: ""
        type: string
      expires:
        example: "1620000000"
        type: string
      success:
        example: true
        type: boolean
    type: object
  apimodel.ValidateTokenUnauthorizedResponse:
    properties:
      error:
        example: Unauthorized
        type: string
      success:
        example: false
        type: boolean
    type: object
  icanteen.ICanteenDay:
    properties:
      day:
        type: string
      lunches:
        items:
          $ref: '#/definitions/icanteen.ICanteenLunch'
        type: array
    type: object
  icanteen.ICanteenLunch:
    properties:
      can_order:
        type: boolean
      name:
        type: string
      ordered:
        type: boolean
    type: object
  model.Class:
    properties:
      classroomid:
        type: string
      grade:
        type: string
      id:
        type: string
      name:
        type: string
      short:
        type: string
      teacher2id:
        type: string
      teacherid:
        type: string
    type: object
  model.Classroom:
    properties:
      id:
        type: string
      name:
        type: string
      short:
        type: string
    type: object
  model.Homework:
    properties:
      attachements: {}
      autor_meno:
        type: string
      data:
        $ref: '#/definitions/model.StringJsonObject'
      datecreated:
        type: string
      datefrom:
        type: string
      datetimefrom:
        type: string
      datetimeto:
        type: string
      dateto:
        type: string
      details:
        type: string
      e_superid:
        type: string
      etestAnswerCards:
        type: integer
      etestCards:
        type: integer
      homeworkid:
        type: string
      hwkid:
        type: string
      missingNextLesson:
        type: boolean
      name:
        type: string
      period: {}
      planid:
        type: string
      pocet_done:
        type: string
      pocet_like:
        type: string
      pocet_reakcii:
        type: string
      posledny_vysledok:
        type: string
      predmet_meno:
        type: string
      predmetid:
        type: string
      skoncil: {}
      skupiny:
        items:
          type: string
        type: array
      stav:
        type: string
      stavhodnotetimelinePathd:
        type: string
      students_hidden:
        type: string
      studyTopics:
        type: boolean
      testid:
        type: string
      timestamp:
        type: string
      typ:
        type: string
      userid:
        type: string
      znamky_udalostid: {}
    type: object
  model.StringJsonObject:
    properties:
      value:
        additionalProperties: true
        type: object
    type: object
  model.Subject:
    properties:
      cbhidden:
        type: boolean
      id:
        type: string
      name:
        type: string
      short:
        type: string
    type: object
  model.Teacher:
    properties:
      classroomid:
        type: string
      datefrom:
        type: string
      dateto:
        type: string
      firstname:
        type: string
      gender:
        type: string
      id:
        type: string
      isout:
        type: boolean
      lastname:
        type: string
      short:
        type: string
    type: object
  model.Timeline:
    properties:
      homeworks:
        additionalProperties:
          $ref: '#/definitions/model.Homework'
        type: object
      items:
        additionalProperties:
          $ref: '#/definitions/model.TimelineItem'
        type: object
    type: object
  model.TimelineItem:
    properties:
      cas_pridania:
        type: string
      cas_pridania_btc:
        type: string
      cas_udalosti:
        type: string
      cas_udalosti_btc:
        type: string
      data:
        $ref: '#/definitions/model.StringJsonObject'
      ineid:
        type: string
      poct_reakcii:
        type: integer
      pomocny_zaznam:
        type: string
      posledna_reakcia:
        type: string
      reakcia_na:
        type: string
      removed:
        type: string
      target_user:
        type: string
      text:
        type: string
      timelineid:
        type: string
      timestamp:
        type: string
      typ:
        type: string
      user:
        type: string
      user_meno:
        type: string
      vlastnik:
        type: string
      vlastnik_meno:
        type: string
    type: object
info:
  contact: {}
  description: JWT authorization token
  title: EduPage2 API
  version: "1.0"
paths:
  /api/classroom/{id}:
    get:
      description: Returns the classroom by ID.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Classroom ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Classroom'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the classroom by ID
      tags:
      - DBI
  /api/subject/{id}:
    get:
      description: Returns the subject by ID.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Subject ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subject'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the subject by ID
      tags:
      - DBI
  /api/teacher/{id}:
    get:
      description: Returns the teacher by ID.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Teacher ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Teacher'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the teacher by ID
      tags:
      - DBI
  /api/timeline:
    get:
      description: Returns the user's timeline from any date to any other date or
        today.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      - example: "2022-01-01T00:00:00Z"
        in: query
        name: from
        type: string
      - default: time.Now()
        example: "2022-01-01T00:00:00Z"
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Timeline'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the user's timeline
      tags:
      - timeline
  /api/timeline/recent:
    get:
      description: Returns the user's timeline from today to 30 days in the past.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Timeline'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the user's recent timeline
      tags:
      - timeline
  /api/timetable:
    get:
      description: Returns the user's timetable from date specified to date specified
        or today.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      - example: "2022-01-01T00:00:00Z"
        in: query
        name: from
        type: string
      - default: time.Now()
        example: "2022-01-01T00:00:00Z"
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.CompleteTimetable'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the user's  timetable
      tags:
      - timetable
  /api/timetable/recent:
    get:
      description: Returns the user's timetable from before yesterday to 7 days in
        the future.
      parameters:
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.CompleteTimetable'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.InternalErrorResponse'
      security:
      - Bearer: []
      summary: Get the user's recent timetable
      tags:
      - timetable
  /icanteen:
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: Loads the lunches from iCanteen for the next month.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Server
        in: formData
        name: server
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/icanteen.ICanteenDay'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodel.ICanteenBadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.ICanteenInternalErrorResponse'
      summary: Load lunches from iCanteen
      tags:
      - lunches
  /login:
    post:
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: Logs in to your Edupage account using the provided credentials.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Server
        in: formData
        name: server
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.LoginSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodel.LoginBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.LoginUnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodel.LoginInternalErrorResponse'
      summary: Login to your Edupage account
      tags:
      - auth
  /validate-token:
    get:
      description: Validates your token and returns a 200 OK if it's valid.
      parameters:
      - description: JWT token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodel.ValidateTokenSuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodel.ValidateTokenUnauthorizedResponse'
      summary: Validate your token
      tags:
      - auth
swagger: "2.0"
