basePath: /
definitions:
  main.LoginBadRequestResponse:
    properties:
      error:
        example: Username and Password are required
        type: string
      success:
        example: false
        type: boolean
    type: object
  main.LoginInternalErrorResponse:
    properties:
      error:
        example: 'failed to login: Post https://example.edupage.org/login/edubarLogin.php:
          dial tcp: lookup example.edupage.org: no such host'
        type: string
      success:
        example: false
        type: boolean
    type: object
  main.LoginRequestUsernamePassword:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  main.LoginRequestUsernamePasswordServer:
    properties:
      password:
        type: string
      server:
        type: string
      username:
        type: string
    required:
    - password
    - server
    - username
    type: object
  main.LoginSuccessResponse:
    properties:
      error:
        example: ""
        type: string
      firstname:
        example: John
        type: string
      lastname:
        example: Doe
        type: string
      success:
        example: true
        type: boolean
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM
        type: string
    type: object
  main.LoginUnauthorizedResponse:
    properties:
      error:
        example: Unexpected response from server, make sure credentials are specified
          correctly
        type: string
      success:
        example: false
        type: boolean
    type: object
info:
  contact: {}
  description: This is the backend for the EduPage2 app.
  title: EduPage2 API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      - multipart/form-data
      - application/x-www-form-urlencoded
      description: Logs in to your Edupage account using the provided credentials.
      parameters:
      - description: Login using username and password
        in: body
        name: login
        schema:
          $ref: '#/definitions/main.LoginRequestUsernamePassword'
      - description: Login using username, password and server
        in: body
        name: loginServer
        schema:
          $ref: '#/definitions/main.LoginRequestUsernamePasswordServer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.LoginBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.LoginUnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.LoginInternalErrorResponse'
      summary: Login to your Edupage account
      tags:
      - auth
swagger: "2.0"
