name: Test Go packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  icanteen:
    name: Run iCanteen package tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test iCanteen package
        run: go test -v ./icanteen -server="${{ secrets.IC_SERVER }}" -username="${{ secrets.IC_USERNAME }}" -password="${{ secrets.IC_PASSWORD }}" -race -coverprofile=coverage.out -covermode=atomic
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}      