name: Test Go packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  icanteen:
    name: Run package tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Copy config.yaml file to cmd/server
        run: |
          sed -i 's/blacklist: false/blacklist: true/g' config.yaml
          cp config.example.yaml cmd/server/config.yaml

      - name: Install swaggo/swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g server.go -d "cmd/server,edupage,icanteen" --pd --parseInternal

      - name: Test packages
        run: go test -v -coverpkg=./... ./... -server="${{ secrets.SERVER }}" -username="${{ secrets.USERNAME }}" -password="${{ secrets.PASSWORD }}" -name="${{ secrets.NAME }}" -ic_server="${{ secrets.IC_SERVER }}" -ic_username="${{ secrets.IC_USERNAME }}" -ic_password="${{ secrets.IC_PASSWORD }}" -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        if: ${{ success() || failure() }}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
